name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Go
        uses: lhotari/action-upterm@v1

