name: CI

on:
  push:
  schedule:
    - cron: '49 */9 * * *'  # every 2 hours at minute 4


jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: chcksm
        run: python scripts/generate.sh

